apiVersion: apps/v1
kind: Deployment
metadata:
  name: microlab-app1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: microlab-app1
  template:
    metadata:
      labels:
        app: microlab-app1
    spec:
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: microlab-app1
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
          {{- with .Values.env }}
          {{- range $key, $val := . }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}
